### ISSUE TITLE
First (Ansible Galaxy) release checklist

### ISSUE THREAD

**Issue by t0mk** [equinix-labs/ansible-collection-equinix#2]
- [ ] remove debug prints (`import q`)
- [ ] make sure equinix-python is already released in PyPi
- [ ] add examples
- [ ] add DEVELOPING.md
- [ ] add RELEASE.md
